git:
  paging:
    colorArg: always
    pager: delta --paging=never
gui:
  sidePanelWidth: 0.15
  theme:
    selectedLineBgColor:
      - underline
    selectedRangeBgColor:
      - underline
refresher:
  refreshInterval: 3
os:
  edit: "nvim"
